### PR TITLE
tests: update nested fakeinstaller test to to boot

### PR DESCRIPTION
**Pull request by mvo5**

### CODE REVIEW

**Comment by mvo5** [comment]
Not quite ready yet, it does not boot yet, sadly not much output:
```
[    1.120166] systemd[1]: plymouth-start.service: Job snap-initramfs-mounts.service/start deleted to break ordering cycle starting with plymouth-start.service/start
```
but maybe a red-herring

**Comment by mvo5** [comment]
and it seems to be not working because `snap prepare-image --classic \
      --channel=edge \
      --snap ./pc-kernel.snap \
      my.model \
      ./classic-seed` does not put an unasserted kernel into the seed :/

**Review by alfonsosanchezbeato — APPROVED** [review]
Thank you!

**Comment by alfonsosanchezbeato** [comment]
Thank you!

**Pull request merged**
